#!/usr/bin/expect
# Run a command on an ITS machine over telnet.
# (Work in progress!)

proc respond_load { r } {
    expect -re {[\r\n][0-9]+\.? *[\r\n]}
    send $r
}

proc ummm {} {
    uplevel #0 {spawn telnet dd}
}

proc resp { x y } {
    expect $x
    send $y
}

set timeout 100

ummm
expect_after timeout abort

resp "Fair Share = *%" ":login ats\r"
expect {
	"Detached Tree-- " { send "\177"; expect "To see system" }
	"To see system"
}
expect "\r"
send_user "got newline\n"
send ":vk\r"
expect -ex "*"

#send ":midas .temp._ats;xumm mid\r"

send ":lisp\r"
expect "LISP "
expect "Alloc? "
send "n\r"
send_user "waiting for star\n"
expect -ex "*"
send_user "got star\n"

#send "(load \"libmax;module\")"
send {(progn (terpri) (princ "123456. "))}
respond_load "(status date)"
expect ")\r"
send_user "now a list\n"
send {(princ '(1 2 3 4 5))}
send_user "waiting\n"
expect -re {\) *\r}
send_user "got it\n"
send "(quit)"

set timeout 5
expect {
	timeout { send "\032"; expect ")"; send ":kill\r" }
	":KILL"
}
expect -ex "*"
send ":massacre\r"
expect -ex "*"
send ":logout\r"
expect "Console * Free."
send "\035"
expect "telnet> "
send "quit\r"
expect eof
